name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build PandaPal.app
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.2.2

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Build
        working-directory: PandaPal
        run: |
          xcodebuild \
            -project PandaPal.xcodeproj \
            -scheme PandaPal \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Package app
        working-directory: PandaPal
        run: |
          APP_PATH="build/Build/Products/Release/PandaPal.app"
          ditto -c -k --keepParent "$APP_PATH" PandaPal.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: PandaPal
          path: PandaPal/PandaPal.zip
